# Generated by Django 4.2.6 on 2023-11-06 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_category_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('linked_in_profile', models.URLField(blank=True, help_text='Please Enter Your Linkein Profile url', null=True)),
                ('github_profile', models.URLField(blank=True, help_text='Please Enter Your Github Profile url', null=True)),
                ('cv', models.FileField(help_text='Please Enter Your latest CV', upload_to='cv')),
                ('cover_letter', models.TextField(help_text='Add your Notes Here', max_length=100)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.job')),
            ],
        ),
    ]
