# Generated by Django 4.2.6 on 2023-11-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apply',
            name='cover_letter',
            field=models.TextField(help_text='Add your Notes Here...', max_length=100),
        ),
    ]
